### ISSUE TITLE
fix typos in both description and Readme

### ISSUE THREAD

**Issue by usama-makhzoum** [Alusus/Rows#3]
this can make finding the library much easier. you have mistyped "Alusus" language name as "Alsusu"

**Comment by sarmadka** [comment]
Thanks for pointing this out. Will push a fix soon.

**Comment by sarmadka** [comment]
This is now fixed. Thanks for filing this issue.

**Comment by usama-makhzoum** [comment]
you may need to duplicate the repo to correct description.

**Comment by sarmadka** [comment]
Thanks for pointing that out. Fixed.
